name: Update Contour Helm chart

on:
  schedule:
    - cron: '0 4 * * *' # Runs daily at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: write        # Required for git push.
  pull-requests: write   # Required for gh pr create.

env:
  GOPROXY: https://proxy.golang.org/
  GO_VERSION: 1.26.0

jobs:
  bump-contour-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: update contour helm chart and create pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for gh pr create.
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        ./hack/actions/update-and-create-pr.sh --real-run
